zone:
  zone_id: zone-2
  area_id: area-1
  robots:
    - robot-201
    - robot-202
    - robot-203
    - robot-204
    - robot-205
    - robot-206
    - robot-207
    - robot-208
    - robot-209
    - robot-210
    - robot-211
    - robot-212
    - robot-213
    - robot-214
    - robot-215
    - robot-216
    - robot-217
    - robot-218
    - robot-219
    - robot-220
    - robot-221
    - robot-222
    - robot-223
    - robot-224
    - robot-225
    - robot-226
    - robot-227
    - robot-228
    - robot-229
    - robot-230
    - robot-231
    - robot-232
    - robot-233
    - robot-234
    - robot-235
    - robot-236
    - robot-237
    - robot-238
    - robot-239
    - robot-240
    - robot-241
    - robot-242
    - robot-243
    - robot-244
    - robot-245
    - robot-246
    - robot-247
    - robot-248
    - robot-249
    - robot-250
    - robot-251
    - robot-252
    - robot-253
    - robot-254
    - robot-255
    - robot-256
    - robot-257
    - robot-258
    - robot-259
    - robot-260
    - robot-261
    - robot-262
    - robot-263
    - robot-264
    - robot-265
    - robot-266
    - robot-267
    - robot-268
    - robot-269
    - robot-270
    - robot-271
    - robot-272
    - robot-273
    - robot-274
    - robot-275
    - robot-276
    - robot-277
    - robot-278
    - robot-279
    - robot-280
    - robot-281
    - robot-282
    - robot-283
    - robot-284
    - robot-285
    - robot-286
    - robot-287
    - robot-288
    - robot-289
    - robot-290
    - robot-291
    - robot-292
    - robot-293
    - robot-294
    - robot-295
    - robot-296
    - robot-297
    - robot-298
    - robot-299
    - robot-300
    - robot-301
    - robot-302
    - robot-303
    - robot-304
    - robot-305
    - robot-306
    - robot-307
    - robot-308
    - robot-309
    - robot-310
    - robot-311
    - robot-312
    - robot-313
    - robot-314
    - robot-315
    - robot-316
    - robot-317
    - robot-318
    - robot-319
    - robot-320
    - robot-321
    - robot-322
    - robot-323
    - robot-324
    - robot-325
    - robot-326
    - robot-327
    - robot-328
    - robot-329
    - robot-330
    - robot-331
    - robot-332
    - robot-333
    - robot-334
    - robot-335
    - robot-336
    - robot-337
    - robot-338
    - robot-339
    - robot-340
    - robot-341
    - robot-342
    - robot-343
    - robot-344
    - robot-345
    - robot-346
    - robot-347
    - robot-348
    - robot-349
    - robot-350
    - robot-351
    - robot-352
    - robot-353
    - robot-354
    - robot-355
    - robot-356
    - robot-357
    - robot-358
    - robot-359
    - robot-360
    - robot-361
    - robot-362
    - robot-363
    - robot-364
    - robot-365
    - robot-366
    - robot-367
    - robot-368
    - robot-369
    - robot-370
    - robot-371
    - robot-372
    - robot-373
    - robot-374
    - robot-375
    - robot-376
    - robot-377
    - robot-378
    - robot-379
    - robot-380
    - robot-381
    - robot-382
    - robot-383
    - robot-384
    - robot-385
    - robot-386
    - robot-387
    - robot-388
    - robot-389
    - robot-390
    - robot-391
    - robot-392
    - robot-393
    - robot-394
    - robot-395
    - robot-396
    - robot-397
    - robot-398
    - robot-399
    - robot-400
messaging:
  broker: "nats://localhost:4222"
