zone:
  zone_id: zone-5
  area_id: area-1
  robots:
    - robot-801
    - robot-802
    - robot-803
    - robot-804
    - robot-805
    - robot-806
    - robot-807
    - robot-808
    - robot-809
    - robot-810
    - robot-811
    - robot-812
    - robot-813
    - robot-814
    - robot-815
    - robot-816
    - robot-817
    - robot-818
    - robot-819
    - robot-820
    - robot-821
    - robot-822
    - robot-823
    - robot-824
    - robot-825
    - robot-826
    - robot-827
    - robot-828
    - robot-829
    - robot-830
    - robot-831
    - robot-832
    - robot-833
    - robot-834
    - robot-835
    - robot-836
    - robot-837
    - robot-838
    - robot-839
    - robot-840
    - robot-841
    - robot-842
    - robot-843
    - robot-844
    - robot-845
    - robot-846
    - robot-847
    - robot-848
    - robot-849
    - robot-850
    - robot-851
    - robot-852
    - robot-853
    - robot-854
    - robot-855
    - robot-856
    - robot-857
    - robot-858
    - robot-859
    - robot-860
    - robot-861
    - robot-862
    - robot-863
    - robot-864
    - robot-865
    - robot-866
    - robot-867
    - robot-868
    - robot-869
    - robot-870
    - robot-871
    - robot-872
    - robot-873
    - robot-874
    - robot-875
    - robot-876
    - robot-877
    - robot-878
    - robot-879
    - robot-880
    - robot-881
    - robot-882
    - robot-883
    - robot-884
    - robot-885
    - robot-886
    - robot-887
    - robot-888
    - robot-889
    - robot-890
    - robot-891
    - robot-892
    - robot-893
    - robot-894
    - robot-895
    - robot-896
    - robot-897
    - robot-898
    - robot-899
    - robot-900
    - robot-901
    - robot-902
    - robot-903
    - robot-904
    - robot-905
    - robot-906
    - robot-907
    - robot-908
    - robot-909
    - robot-910
    - robot-911
    - robot-912
    - robot-913
    - robot-914
    - robot-915
    - robot-916
    - robot-917
    - robot-918
    - robot-919
    - robot-920
    - robot-921
    - robot-922
    - robot-923
    - robot-924
    - robot-925
    - robot-926
    - robot-927
    - robot-928
    - robot-929
    - robot-930
    - robot-931
    - robot-932
    - robot-933
    - robot-934
    - robot-935
    - robot-936
    - robot-937
    - robot-938
    - robot-939
    - robot-940
    - robot-941
    - robot-942
    - robot-943
    - robot-944
    - robot-945
    - robot-946
    - robot-947
    - robot-948
    - robot-949
    - robot-950
    - robot-951
    - robot-952
    - robot-953
    - robot-954
    - robot-955
    - robot-956
    - robot-957
    - robot-958
    - robot-959
    - robot-960
    - robot-961
    - robot-962
    - robot-963
    - robot-964
    - robot-965
    - robot-966
    - robot-967
    - robot-968
    - robot-969
    - robot-970
    - robot-971
    - robot-972
    - robot-973
    - robot-974
    - robot-975
    - robot-976
    - robot-977
    - robot-978
    - robot-979
    - robot-980
    - robot-981
    - robot-982
    - robot-983
    - robot-984
    - robot-985
    - robot-986
    - robot-987
    - robot-988
    - robot-989
    - robot-990
    - robot-991
    - robot-992
    - robot-993
    - robot-994
    - robot-995
    - robot-996
    - robot-997
    - robot-998
    - robot-999
    - robot-1000
messaging:
  broker: "nats://localhost:4222"
