zone:
  zone_id: zone-1
  area_id: area-1
  robots:
    - robot-1
    - robot-2
    - robot-3
    - robot-4
    - robot-5
    - robot-6
    - robot-7
    - robot-8
    - robot-9
    - robot-10
    - robot-11
    - robot-12
    - robot-13
    - robot-14
    - robot-15
    - robot-16
    - robot-17
    - robot-18
    - robot-19
    - robot-20
    - robot-21
    - robot-22
    - robot-23
    - robot-24
    - robot-25
    - robot-26
    - robot-27
    - robot-28
    - robot-29
    - robot-30
    - robot-31
    - robot-32
    - robot-33
    - robot-34
    - robot-35
    - robot-36
    - robot-37
    - robot-38
    - robot-39
    - robot-40
    - robot-41
    - robot-42
    - robot-43
    - robot-44
    - robot-45
    - robot-46
    - robot-47
    - robot-48
    - robot-49
    - robot-50
    - robot-51
    - robot-52
    - robot-53
    - robot-54
    - robot-55
    - robot-56
    - robot-57
    - robot-58
    - robot-59
    - robot-60
    - robot-61
    - robot-62
    - robot-63
    - robot-64
    - robot-65
    - robot-66
    - robot-67
    - robot-68
    - robot-69
    - robot-70
    - robot-71
    - robot-72
    - robot-73
    - robot-74
    - robot-75
    - robot-76
    - robot-77
    - robot-78
    - robot-79
    - robot-80
    - robot-81
    - robot-82
    - robot-83
    - robot-84
    - robot-85
    - robot-86
    - robot-87
    - robot-88
    - robot-89
    - robot-90
    - robot-91
    - robot-92
    - robot-93
    - robot-94
    - robot-95
    - robot-96
    - robot-97
    - robot-98
    - robot-99
    - robot-100
    - robot-101
    - robot-102
    - robot-103
    - robot-104
    - robot-105
    - robot-106
    - robot-107
    - robot-108
    - robot-109
    - robot-110
    - robot-111
    - robot-112
    - robot-113
    - robot-114
    - robot-115
    - robot-116
    - robot-117
    - robot-118
    - robot-119
    - robot-120
    - robot-121
    - robot-122
    - robot-123
    - robot-124
    - robot-125
    - robot-126
    - robot-127
    - robot-128
    - robot-129
    - robot-130
    - robot-131
    - robot-132
    - robot-133
    - robot-134
    - robot-135
    - robot-136
    - robot-137
    - robot-138
    - robot-139
    - robot-140
    - robot-141
    - robot-142
    - robot-143
    - robot-144
    - robot-145
    - robot-146
    - robot-147
    - robot-148
    - robot-149
    - robot-150
    - robot-151
    - robot-152
    - robot-153
    - robot-154
    - robot-155
    - robot-156
    - robot-157
    - robot-158
    - robot-159
    - robot-160
    - robot-161
    - robot-162
    - robot-163
    - robot-164
    - robot-165
    - robot-166
    - robot-167
    - robot-168
    - robot-169
    - robot-170
    - robot-171
    - robot-172
    - robot-173
    - robot-174
    - robot-175
    - robot-176
    - robot-177
    - robot-178
    - robot-179
    - robot-180
    - robot-181
    - robot-182
    - robot-183
    - robot-184
    - robot-185
    - robot-186
    - robot-187
    - robot-188
    - robot-189
    - robot-190
    - robot-191
    - robot-192
    - robot-193
    - robot-194
    - robot-195
    - robot-196
    - robot-197
    - robot-198
    - robot-199
    - robot-200
messaging:
  broker: "nats://localhost:4222"
