zone:
  zone_id: zone-3
  area_id: area-1
  robots:
    - robot-401
    - robot-402
    - robot-403
    - robot-404
    - robot-405
    - robot-406
    - robot-407
    - robot-408
    - robot-409
    - robot-410
    - robot-411
    - robot-412
    - robot-413
    - robot-414
    - robot-415
    - robot-416
    - robot-417
    - robot-418
    - robot-419
    - robot-420
    - robot-421
    - robot-422
    - robot-423
    - robot-424
    - robot-425
    - robot-426
    - robot-427
    - robot-428
    - robot-429
    - robot-430
    - robot-431
    - robot-432
    - robot-433
    - robot-434
    - robot-435
    - robot-436
    - robot-437
    - robot-438
    - robot-439
    - robot-440
    - robot-441
    - robot-442
    - robot-443
    - robot-444
    - robot-445
    - robot-446
    - robot-447
    - robot-448
    - robot-449
    - robot-450
    - robot-451
    - robot-452
    - robot-453
    - robot-454
    - robot-455
    - robot-456
    - robot-457
    - robot-458
    - robot-459
    - robot-460
    - robot-461
    - robot-462
    - robot-463
    - robot-464
    - robot-465
    - robot-466
    - robot-467
    - robot-468
    - robot-469
    - robot-470
    - robot-471
    - robot-472
    - robot-473
    - robot-474
    - robot-475
    - robot-476
    - robot-477
    - robot-478
    - robot-479
    - robot-480
    - robot-481
    - robot-482
    - robot-483
    - robot-484
    - robot-485
    - robot-486
    - robot-487
    - robot-488
    - robot-489
    - robot-490
    - robot-491
    - robot-492
    - robot-493
    - robot-494
    - robot-495
    - robot-496
    - robot-497
    - robot-498
    - robot-499
    - robot-500
    - robot-501
    - robot-502
    - robot-503
    - robot-504
    - robot-505
    - robot-506
    - robot-507
    - robot-508
    - robot-509
    - robot-510
    - robot-511
    - robot-512
    - robot-513
    - robot-514
    - robot-515
    - robot-516
    - robot-517
    - robot-518
    - robot-519
    - robot-520
    - robot-521
    - robot-522
    - robot-523
    - robot-524
    - robot-525
    - robot-526
    - robot-527
    - robot-528
    - robot-529
    - robot-530
    - robot-531
    - robot-532
    - robot-533
    - robot-534
    - robot-535
    - robot-536
    - robot-537
    - robot-538
    - robot-539
    - robot-540
    - robot-541
    - robot-542
    - robot-543
    - robot-544
    - robot-545
    - robot-546
    - robot-547
    - robot-548
    - robot-549
    - robot-550
    - robot-551
    - robot-552
    - robot-553
    - robot-554
    - robot-555
    - robot-556
    - robot-557
    - robot-558
    - robot-559
    - robot-560
    - robot-561
    - robot-562
    - robot-563
    - robot-564
    - robot-565
    - robot-566
    - robot-567
    - robot-568
    - robot-569
    - robot-570
    - robot-571
    - robot-572
    - robot-573
    - robot-574
    - robot-575
    - robot-576
    - robot-577
    - robot-578
    - robot-579
    - robot-580
    - robot-581
    - robot-582
    - robot-583
    - robot-584
    - robot-585
    - robot-586
    - robot-587
    - robot-588
    - robot-589
    - robot-590
    - robot-591
    - robot-592
    - robot-593
    - robot-594
    - robot-595
    - robot-596
    - robot-597
    - robot-598
    - robot-599
    - robot-600
messaging:
  broker: "nats://localhost:4222"
