zone:
  zone_id: zone-4
  area_id: area-1
  robots:
    - robot-601
    - robot-602
    - robot-603
    - robot-604
    - robot-605
    - robot-606
    - robot-607
    - robot-608
    - robot-609
    - robot-610
    - robot-611
    - robot-612
    - robot-613
    - robot-614
    - robot-615
    - robot-616
    - robot-617
    - robot-618
    - robot-619
    - robot-620
    - robot-621
    - robot-622
    - robot-623
    - robot-624
    - robot-625
    - robot-626
    - robot-627
    - robot-628
    - robot-629
    - robot-630
    - robot-631
    - robot-632
    - robot-633
    - robot-634
    - robot-635
    - robot-636
    - robot-637
    - robot-638
    - robot-639
    - robot-640
    - robot-641
    - robot-642
    - robot-643
    - robot-644
    - robot-645
    - robot-646
    - robot-647
    - robot-648
    - robot-649
    - robot-650
    - robot-651
    - robot-652
    - robot-653
    - robot-654
    - robot-655
    - robot-656
    - robot-657
    - robot-658
    - robot-659
    - robot-660
    - robot-661
    - robot-662
    - robot-663
    - robot-664
    - robot-665
    - robot-666
    - robot-667
    - robot-668
    - robot-669
    - robot-670
    - robot-671
    - robot-672
    - robot-673
    - robot-674
    - robot-675
    - robot-676
    - robot-677
    - robot-678
    - robot-679
    - robot-680
    - robot-681
    - robot-682
    - robot-683
    - robot-684
    - robot-685
    - robot-686
    - robot-687
    - robot-688
    - robot-689
    - robot-690
    - robot-691
    - robot-692
    - robot-693
    - robot-694
    - robot-695
    - robot-696
    - robot-697
    - robot-698
    - robot-699
    - robot-700
    - robot-701
    - robot-702
    - robot-703
    - robot-704
    - robot-705
    - robot-706
    - robot-707
    - robot-708
    - robot-709
    - robot-710
    - robot-711
    - robot-712
    - robot-713
    - robot-714
    - robot-715
    - robot-716
    - robot-717
    - robot-718
    - robot-719
    - robot-720
    - robot-721
    - robot-722
    - robot-723
    - robot-724
    - robot-725
    - robot-726
    - robot-727
    - robot-728
    - robot-729
    - robot-730
    - robot-731
    - robot-732
    - robot-733
    - robot-734
    - robot-735
    - robot-736
    - robot-737
    - robot-738
    - robot-739
    - robot-740
    - robot-741
    - robot-742
    - robot-743
    - robot-744
    - robot-745
    - robot-746
    - robot-747
    - robot-748
    - robot-749
    - robot-750
    - robot-751
    - robot-752
    - robot-753
    - robot-754
    - robot-755
    - robot-756
    - robot-757
    - robot-758
    - robot-759
    - robot-760
    - robot-761
    - robot-762
    - robot-763
    - robot-764
    - robot-765
    - robot-766
    - robot-767
    - robot-768
    - robot-769
    - robot-770
    - robot-771
    - robot-772
    - robot-773
    - robot-774
    - robot-775
    - robot-776
    - robot-777
    - robot-778
    - robot-779
    - robot-780
    - robot-781
    - robot-782
    - robot-783
    - robot-784
    - robot-785
    - robot-786
    - robot-787
    - robot-788
    - robot-789
    - robot-790
    - robot-791
    - robot-792
    - robot-793
    - robot-794
    - robot-795
    - robot-796
    - robot-797
    - robot-798
    - robot-799
    - robot-800
messaging:
  broker: "nats://localhost:4222"
