apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmms
  namespace: robotfleetos
  labels:
    app: cmms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmms
  template:
    metadata:
      labels:
        app: cmms
    spec:
      containers:
        - name: cmms
          image: robotfleetos/robotfleetos:latest
          imagePullPolicy: IfNotPresent
          command: ["./bin/cmms"]
          ports:
            - containerPort: 8085
          env:
            - name: FLEET_API_URL
              value: "http://fleet:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: cmms
  namespace: robotfleetos
spec:
  selector:
    app: cmms
  ports:
    - port: 8085
      targetPort: 8085
      name: http
