apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: robotfleetos

resources:
  - namespace.yaml
  - fleet.yaml
  - mes.yaml
  - wms.yaml
  - traceability.yaml
  - qms.yaml
  - cmms.yaml
  - plm.yaml
  - erp.yaml

# Override image when building/pushing to your registry:
# images:
#   - name: robotfleetos/robotfleetos:latest
#     newName: ghcr.io/hansstam86/robotfleetos
#     newTag: latest
