apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes
  namespace: robotfleetos
  labels:
    app: mes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mes
  template:
    metadata:
      labels:
        app: mes
    spec:
      containers:
        - name: mes
          image: robotfleetos/robotfleetos:latest
          imagePullPolicy: IfNotPresent
          command: ["./bin/mes"]
          ports:
            - containerPort: 8081
          env:
            - name: FLEET_API_URL
              value: "http://fleet:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: mes
  namespace: robotfleetos
spec:
  selector:
    app: mes
  ports:
    - port: 8081
      targetPort: 8081
      name: http
