apiVersion: apps/v1
kind: Deployment
metadata:
  name: plm
  namespace: robotfleetos
  labels:
    app: plm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plm
  template:
    metadata:
      labels:
        app: plm
    spec:
      containers:
        - name: plm
          image: robotfleetos/robotfleetos:latest
          imagePullPolicy: IfNotPresent
          command: ["./bin/plm"]
          ports:
            - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: plm
  namespace: robotfleetos
spec:
  selector:
    app: plm
  ports:
    - port: 8086
      targetPort: 8086
      name: http
